# напиши здесь код для второго экрана приложения
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QVBoxLayout, QHBoxLayout, QLineEdit

#def first_task():


app = QApplication([])
main_win2 = QWidget()
main_win2.setWindowTitle('Тест Руфье: проведение')
main_win2.move(460, 170)
main_win2.resize(1000, 600)
name = QLabel('Введите Ф.И.О')
name_edit = QLineEdit()
age = QLabel('Полных лет:')
age_edit = QLineEdit()
instr_1 = QLabel('Лягьте на спину и замерьте пульс за 15 секунд. \nНажмите на кнопку "Начать первый тест" и впишите результат в соответствующее поле.')
button_1 = QPushButton('Начать первый тест')
instr_1_edit = QLineEdit()
instr_2 = QLabel('Выполните 30 приседаний за 45 секунд. \nДля этого нажмите на кнопку "Начать делать приседания", чтобы запустить счётчик.')
button_2 = QPushButton('Начать делать приседания')
instr_3 = QLabel('Лягте на спину и замерьте пульс сначала за первые 15 секунд минуты, а затем за последние 15 секунд. \n Нажмите на кнопку "Начать финальный тест", чтобы запустить таймер. \nЗелёным обозначены секунды, в течении которых необходимо проводить измерения, а чёрным - секунды без замера пульсаций. \nРезультаты запишите в соответствующие поля.')
button_3 = QPushButton('Начать финальный тест')
instr_3_edit_1 = QLineEdit()
instr_3_edit_2 = QLineEdit()
final_button = QPushButton('Отправить результаты')
line_tasks = QLabel('00:00:15')
line_v1 = QVBoxLayout()
line_v2 = QVBoxLayout()
line_h1 = QHBoxLayout()
line_v1.addWidget(name, alignment = Qt.AlignLeft)
line_v1.addWidget(name_edit, alignment = Qt.AlignLeft)
line_v1.addWidget(age, alignment = Qt.AlignLeft)
line_v1.addWidget(age_edit, alignment = Qt.AlignLeft)
line_v1.addWidget(instr_1, alignment = Qt.AlignLeft)
line_v1.addWidget(button_1, alignment = Qt.AlignLeft)
line_v1.addWidget(instr_1_edit, alignment = Qt.AlignLeft)
line_v2.addWidget(line_tasks, alignment = Qt.AlignRight)
line_v1.addWidget(instr_2, alignment = Qt.AlignLeft)
line_v1.addWidget(button_2, alignment = Qt.AlignLeft)
line_v1.addWidget(instr_3, alignment = Qt.AlignLeft)
line_v1.addWidget(button_3, alignment = Qt.AlignLeft)
line_v1.addWidget(instr_3_edit_1, alignment = Qt.AlignLeft)
line_v1.addWidget(instr_3_edit_2, alignment = Qt.AlignLeft)
line_v1.addWidget(final_button, alignment = Qt.AlignCenter)
line_h1.addLayout(line_v1)
line_h1.addLayout(line_v2)
main_win2.setLayout(line_h1)
#button_1.clicked.connect(first_task)
main_win2.show()
app.exec_()